---
title: "GridCAT Mask Comparison"
author: "C Newton"
date: "February 19, 2021"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

# Stats on gridcode metrics 
require(ggplot2)
library(tidyverse)
require(readxl)
require(RColorBrewer)
require(ggthemes)
require(RColorBrewer)
require(ggthemes)
require(lme4)

# load in data
gridOrig_in = read_csv('/lustre/scratch/wbic-beta/ccn30/ENCRYPT/fMRI/gridcellpilot/results/$csv_result_files/gridCAT_final_X_results_meanOri.csv');
gridMaass_in = read_csv('/lustre/scratch/wbic-beta/ccn30/ENCRYPT/fMRI/gridcellpilot/results/$csv_result_files/gridCAT_Maass_X_results.csv');

# add demographic data to Maass masks
gridMaass_in <- cbind(gridMaass_in,gridOrig_in[ ,2:3])

# extract magnitude data from Orig for pm/al 6 fold
gridmag.untidy <- gridOrig_in %>% select(Subject,Age,Gender,starts_with("GCmagnitude")) 
gridmag.gather <- gridmag.untidy %>% gather(Model,Grid_Magnitude,starts_with("GCmag"))
gridmag.Orig <- separate(gridmag.gather,Model,c(NA,"Run","Side",NA,NA,"ROI"),"_")
gridmag.Orig <- gridmag.Orig %>% add_column(Mask = "Manual")
gridmag.Orig.main <- gridmag.Orig %>% filter(ROI %in% c("pmRight6","pmLeft6","alRight6","alLeft6"))
rm(gridmag.gather,gridmag.untidy)

# extract magntidue data from Maass
gridmag.untidy <- gridMaass_in %>% select(Subject,Age,Gender,starts_with("GCmagnitude")) 
gridmag.gather <- gridmag.untidy %>% gather(Model,Grid_Magnitude,starts_with("GCmag"))
gridmag.Maass <- separate(gridmag.gather,Model,c(NA,"Run","Side","ROI"),"_")
rm(gridmag.gather,gridmag.untidy)
gridmag.Maass <- gridmag.Maass %>% add_column(Mask = "Maass")

# combine Orig and Mag, make factors
gridmag <- rbind(gridmag.Orig.main, gridmag.Maass)
gridmag <- gridmag %>% modify_if(is.character,as.factor)
gridmag
```
## Pilot comparison
### Plot grid cell magnitude per mask type
```{r}
pd <- position_dodge(0.2)
gridmag.allruns <- gridmag %>% filter(Run %in% "allRuns")
ggplot(gridmag.allruns, aes(Side,Grid_Magnitude)) +
  geom_boxplot(aes(fill=ROI),outlier.shape = NA,alpha=0.6, show.legend = TRUE) +
  scale_fill_brewer(palette="YlGnBu") +
  facet_wrap(~Mask)

```

# Explore tSNR
```{bash}
# make EC subdiv masks
pathstem=/home/ccn30/rds/hpc-work/WBIC_lustre/ENCRYPT

#mysubjs=${pathstem}/ENCRYPT_MasterRIScodes.txt
mysubjs=${pathstem}/testsubjcode.txt

## make tSNR images for each subject
for subjID in `cat $mysubjs`
do
subject="$(cut -d'/' -f1 <<<"$subjID")"
echo "******** starting $subject ********"

# set paths to inputs
maskDir=/home/ccn30/rds/rds-p00500_encrypt-URQgmO1brZ0/p00500/ENCRYPT_MTLmasks/"${subject}"
echo $maskDir
#regDir=${pathstem}/registrations/"${subject}"
EPI=/home/ccn30/rds/rds-p00500_encrypt-URQgmO1brZ0/p00500/ENCRYPT_images/"${subject}"/fMRI/rtopup_run1.nii
#rightpmECT2xEPI=${regDir}/pmEC_right_Magdeburg_HybridMaskT2xEPI.nii
#rightalECT2xEPI=${regDir}/alEC_right_Magdeburg_HybridMaskT2xEPI.nii
#rightpmMaassxEPI=${regDir}/pmEC_right_MaassMaskxEPI.nii
#rightalMaassxEPI=${regDir}/alEC_right_MaassMaskxEPI.nii
ASHS_EC=${maskDir}/ASHS_EC_EPI.nii.gz
HybridDTI_epi_R=${maskDir}/pmEC_right_HybridDTI_EPI.nii.gz
HybridMaass_epi_R=${maskDir}/combinedEC_right_HybridMaass_EPI.nii.gz

# make tSNR images
tSNRdir=${pathstem}/results/tSNR/"${subject}"
mkdir -p $tSNRdir
EPI_mean=$tSNRdir/EPI_mean.nii
EPI_SD=$tSNRdir/EPI_SD.nii
EPI_tSNR=$tSNRdir/EPI_tSNR.nii
fslmaths $EPI -Tmean $EPI_mean 
fslmaths $EPI -Tstd $EPI_SD
fslmaths $EPI_mean -div $EPI_SD $EPI_tSNR

# extract values for different masks
ASHS_EC_tSNR=$tSNRdir/tSNR_ASHS_EC_EPI.nii
HybridDTI_epi_R_tSNR=$tSNRdir/tSNR_pmEC_right_HybridDTI_EPI.nii
HybridMaass_epi_R_tSNR=$tSNRdir/tSNR_combinedEC_right_HybridMaass_EPI.nii
fslmaths $EPI_tSNR -mas $ASHS_EC $ASHS_EC_tSNR
fslmaths $EPI_tSNR -mas $HybridDTI_epi_R $HybridDTI_epi_R_tSNR
fslmaths $EPI_tSNR -mas $HybridMaass_epi_R $HybridMaass_epi_R_tSNR

#pmECR_hybridMag_tSNR=$tSNRdir/tSNR_pmEC_right_hybridmaskMag.nii
#alECR_hybridMag_tSNR=$tSNRdir/tSNR_alEC_right_hybridmaskMag.nii
#pmECR_Maass_tSNR=$tSNRdir/tSNR_pmEC_right_Maassmask.nii
#alECR_Maass_tSNR=$tSNRdir/tSNR_alEC_right_Maassmask.nii
#fslmaths $EPI_tSNR -mas $rightpmECT2xEPI $pmECR_hybridMag_tSNR
#fslmaths $EPI_tSNR -mas $rightalECT2xEPI $alECR_hybridMag_tSNR
#fslmaths $EPI_tSNR -mas $rightpmMaassxEPI $pmECR_Maass_tSNR
#fslmaths $EPI_tSNR -mas $rightalMaassxEPI $alECR_Maass_tSNR


# use subshell to output multiple fslstats commands per mask per subject into single output file, converting spaces to commas to output as csv, use >> to append not overwrite
#(fslstats $ASHS_EC_tSNR -V -M -S -R | tr " " ","; fslstats $HybridDTI_epi_R_tSNR -V -M -S -R | tr " " ",";fslstats $HybridMaass_epi_R_tSNR -V -M -S -R | tr " " ",") >> ${pathstem}/results/tSNR/tSNR_output.csv

fslstats $ASHS_EC_tSNR -V -M -S -R | tr " " "," >> $tSNRdir/tSNR_output_EC.csv
fslstats $HybridDTI_epi_R_tSNR -V -M -S -R | tr " " "," >> $tSNRdir/tSNR_output_DTI.csv
fslstats $HybridMaass_epi_R_tSNR -V -M -S -R | tr " " "," >> $tSNRdir/tSNR_output_Maass.csv
cat $tSNRdir/tSNR_output_EC.csv $tSNRdir/tSNR_output_DTI.csv $tSNRdir/tSNR_output_Maass.csv >>  $tSNRdir/tSNR_output_all.csv
printf "$subject,ASHS_EC\n$subject,DTI\n$subject,Maass" >> $tSNRdir/vars.csv
paste -d , $tSNRdir/vars.csv $tSNRdir/tSNR_output_all.csv >> ${pathstem}/results/tSNR/tSNR_output.csv

done 
```



# Now read in tSNR_output.csv to visualise values
```{r}
tSNR_in <- read_csv("/lustre/scratch/wbic-beta/ccn30/ENCRYPT/results/tSNR/tSNR_output.csv")
tSNR_in <- tSNR_in %>% modify_if(is.character,as.factor)
tSNR_in <- tSNR_in[-c(17:36),]

# plot mean tSNR
ggplot(tSNR_in, aes(mask,mean_tSNR)) +
  geom_boxplot(aes(fill=subdivision),outlier.shape = NA,alpha=0.6, show.legend = TRUE)
```

```{r}
# plot mean tSNR
ggplot(tSNR_in, aes(mask,Volume)) +
  geom_boxplot(aes(fill=subdivision),outlier.shape = NA,alpha=0.6, show.legend = TRUE) +
  geom_point(aes(group=subject),size=2,shape=21,position = pd)
```

```{r}
ggplot(tSNR_in, aes(mask,max_tSNR)) +
  geom_boxplot(aes(fill=subdivision),outlier.shape = NA,alpha=0.6, show.legend = TRUE) +
  geom_point(aes(group=subject),size=2,shape=21,position = pd)
```

